apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: master
        image: gcr.io/festive-ray-133923/webapp:v2  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ZEUS_TOKEN
          value: "8dcccc00"
        ports:
        - containerPort: 80