apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: master
        image: gcr.io/festive-ray-133923/webapp:v1  #gcr.io/google_samples/gb-frontend:v10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 80